# Spring properties
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost/cosmicsstore
    username: root
    password: a1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Discovery Server Access
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 1114   # HTTP (Tomcat) port

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus